### PR TITLE
Fix scripted_action + various schedule fixes

### PR DESCRIPTION
**Pull request by zpl-zak**
The promised code fixing scripted_action. Mostly code from the old Spirit codebase. The map I've used to test the fixes is attached below.

Thanks!
[scripted_action.zip](https://github.com/LogicAndTrick/halflife-updated/files/6147778/scripted_action.zip)

### CODE REVIEW

**Comment by LogicAndTrick** [comment]
Thanks so much! The scripted sequence code is something I'm not very familiar with yet, so I'll spend a bit of time looking at the related code before merging, just so I can learn a bit about how it works.

**Comment by zpl-zak** [comment]
The only issue is with `TASK_WAIT_FOR_SCRIPT` as I'm not sure if scripted_action should wait for other clones' NPCs to arrive. At the moment `scripted_action` fires off immediately upon the NPC arriving, unlike with `scripted_sequence` that plays the action anim only after all the NPC arrive at their destination.

Frankly, I am not even sure how it was supposed to be handled originally as I couldn't make scripted_action even work on the Spirit 1.8 old codebase I found. This issue needs some consideration first.

**Comment by LogicAndTrick** [comment]
Ok, so this launched me down a rabbit hole of applying fixes and updates to all my other branches, so now I've finally finished updating them and have come back to this one. I applied the changes from the original Spirit code base (I missed the schedule file entirely, which was causing the issues), but I'm interested in the additional changes you've made.

Do you think they're still useful to merge in? I'm seeing some differences in your code for `TASK_WAIT_FOR_SCRIPT` in both `StartTask` and `RunTask` and I'm wondering if it's just a different approach for the same solution, or if there's some fixes in there too?

**Comment by zpl-zak** [comment]
I will look at the conflict and let you know if the changes you've made would suffice to ensure `scripted_action` works. Thank you for the update on the issue!

**Comment by zpl-zak** [comment]
I had a look, and everything works fine. I don't see any issues in your version. Let's decline this PR. I think we're all good here!

EDIT: Regarding `TASK_WAIT_FOR_SCRIPT`, I had a look at SOHL, and indeed my version differs. I feel it was a mistake on my side, but since your version works fine and doesn't differ in functionality, we're good to close it.

**Comment by LogicAndTrick** [comment]
Great, thanks for looking into it! It really helped me nail down some issues that would have taken me a long time otherwise, so it's very much appreciated!

**Pull request closed without merging**
